### ISSUE TITLE
[bug]: data not found with not in filter(if tag value not exist)

### ISSUE THREAD

**Issue by kevin6025** [lindb/lindb#994]
**Describe the bug**
select * from lindb.monitor.system.cpu_stat where node not in('local') group by node

not data found with not filter if tag value not exist 

**To Reproduce** (Required)

**Expected behavior** (Required)

**What's your LinDB version?** (Required)
0.3.0

**Screenshots**

**Additional context**

**Comment by joyant** [comment]
https://github.com/lindb/lindb/blob/2d5b7ece0542c4f6f2316838a315480d64dd0f4c/query/operator/series_filtering.go#L73

The series filtering operator in Lindb considers it an error when a tag value does not exist. In such cases, SeriesIDsAfterFiltering is empty, resulting in an empty query result.

This may seem a bit illogical, as in the case of a nonexistent specified tag value, it might be better to query for all tag values. However, another perspective could be that the person writing the query should be aware of the tag values associated with the metric, and entering incorrect tag values is not desirable.

If @stone1100  believe this is a bug, I can fix it.

**Comment by stone1100** [comment]
Maybe the root cause is not cache tag filter results in query context when tag value not found doing tag filter.
https://github.com/lindb/lindb/blob/main/query/operator/tag_values_lookup.go#L73-L79

After that will get error when do series filter.
https://github.com/lindb/lindb/blob/2d5b7ece0542c4f6f2316838a315480d64dd0f4c/query/operator/series_filtering.go#L109

I think cache an empty tag filter result can fix this bug. (https://github.com/lindb/lindb/blob/main/query/operator/tag_values_lookup.go#L73-L79)

The not expression filter logic as below:  
1. tag value filter and get tag value ids A => node in('local') 
2. series ids filter based on tag value ids <- go error
3. get all series ids by tag key(node)
4. do Bitmap NotAnd operator

@joyant
